# Docker环境下关闭守护进程
daemon  off;
worker_processes  1;

error_log  /viewlogs/error.log warn;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       /app/nginx/conf/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_iso8601] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /viewlogs/access.log  main;

    charset utf-8;
    
    sendfile       on;
    tcp_nopush     on;
    tcp_nodelay    on;

    keepalive_timeout  65;

    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;

    etag off;

    gzip on;
    gzip_static on;
    gzip_min_length 1k;
    gzip_buffers 4 16k;
    gzip_comp_level 6;
    gzip_types text/plain text/css text/xml text/javascript application/json application/javascript application/x-javascript application/xml image/svg+xml;
    gzip_vary on;

    server_tokens off;

    map $http_origin $cors_whitelist {
        default "";
        # "~^(https?://(.*\.)*hainanwangdai\.com)" $1;
    }

    server {
        listen 8080 default_server;
        server_name  _;
        root  /app/nginx/webapp/dist;

        location /favicon.ico {
            log_not_found off;
            access_log off;
        }

        location /health {
            default_type text/plain;
            return 200 'ok';
        }
        
        # 对指定的静态资源后缀名设置缓存及跨域访问
        location ~ .*\.(css|js|jpg|png|gif|swf|woff|woff2|eot|svg|ttf|otf|mp3|m4a|aac|ico|gz)$ {
            expires 1y;
            add_header Access-Control-Allow-Origin $cors_whitelist;
        }

        location ~ /\. {
           deny  all;
        }

        location / {
            try_files $uri $uri/ /index.html =404;
            add_header Cache-Control no-store;
            add_header Strict-Transport-Security "max-age=172800";
            add_header X-Content-Type-Options "nosniff";
            # add_header X-Frame-Options "SAMEORIGIN"; # Clickjacking Attacks 功能暂时不能开启，部分协议需要允许渠道方通过iframe嵌套引用
            add_header X-XSS-Protection "1; mode=block";
            add_header X-Download-Options "noopen";
        }
    }
}
