let PUBLIC_KEY = `
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqhU0j5x0720itAVNZs7N38GET3XFvV/Hxbh+170eETeEM6f7tEcSvstZBijpL81moQbGRtgJERWgSYrLhn2UaL/XZYH8gDUvCbfHpJintMOrfi9mW7VrYQGAFKsdoyTud9VZ7I0NPTQMXvt180Gi+8x1g/qCODsK2tEgyie8nvIY7tZAYcbFoFTsSZooWJz+lGca0ktqDlM59d8zTIlwHVIcpre2iwqxOIpI/JgfZv5LYKTeyuAXQUyLNoY+Howrvaz7CtZiTVxYGskH8wz7AwlOGfFMH+aKdCJL95Cl5SBtdNZ6yv5akLfUBGQ4zMin29BjFDx/icEACLawLCLPCwIDAQAB
-----END PUBLIC KEY-----
`;

if (
  import.meta.env.VITE_APP_RUNTIME_ENV !== 'prod' &&
  import.meta.env.VITE_APP_RUNTIME_ENV !== 'staging'
) {
  PUBLIC_KEY = `
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAw/CtDFCtagnGk5qGtpRInS37E5QiiZrRzVLTBSehzWnDSY9ZtGSpHOraGMX/mex//mAcAaxP6p2AWP8dfo30J6G4AuL/L3l8NJSekOsvB+J9HNcdRBv2onCFRa0RBYBy9kiw49YjLiCygORwExyjRFJ58O4a1WINdfKmW1EnRyv3HTPUBNOYU3tAHVrADAD5qMUjGx2mmojHRVmB03VkuTxK7CoXU6sv0pr+FGBqHjWs1Wd18csh1Da5ZmDqQr93hUoU8MBzBZMOZsgjmicGFACHNedKzh7mP8/xbFBz2J1zyudo1WIBqCw9meLvrlQiYGSpkFJwPoGjVJQqVINbRQIDAQAB
-----END PUBLIC KEY-----
`;
}

export default PUBLIC_KEY;
